# Generated by Django 5.1.7 on 2025-05-26 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Amount', models.IntegerField()),
                ('Description', models.CharField(blank=True, max_length=200, null=True)),
                ('Type', models.CharField(choices=[('Income', 'Income'), ('Expense', 'Expense')], max_length=100)),
                ('Category', models.CharField(choices=[('Food', 'Food'), ('Travel', 'Travel'), ('Shopping', 'Shopping'), ('Utilities', 'Utilities'), ('Other', 'Other')], default='Other', max_length=10)),
                ('Date', models.DateField()),
            ],
        ),
    ]
