# Generated by Django 5.1.7 on 2025-05-28 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_requestlogs_alter_transaction_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestlogs',
            name='request_method',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
