# Generated by Django 5.1.7 on 2025-05-28 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_requestlogs_request_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestlogs',
            name='request_method',
            field=models.CharField(max_length=50),
        ),
    ]
